site_name: Python Tutorial
site_url: https://bibaijin.github.io/tutorial-python
site_description: Python 的学习心得
site_author: bibaijin

repo_url: https://github.com/bibaijin/tutorial-python

theme: mkdocs
theme_dir: 'custom_theme'

pages:
- 首页: index.md
- Python:
    - Built-in: python/built-in.md
    - Django: python/django.md
    - Matplotlib: python/matplotlib.md
    - MkDocs: python/mkdocs.md
- 关于: about.md

markdown_extensions:
    - smarty
    - sane_lists
    - footnotes
    - tables

copyright: Copyright &copy; 2015 <a href="mailto:bibaijin@gmail.com">金比白</a>.
